/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], */

  // But you can create a sidebar manually

  docs: [
    {
      type: 'doc',
      label: 'ScalarDB Community Docs Home',
      id: 'index',
    },
    {
      type: 'category',
      label: 'About ScalarDB',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'design',
          label: 'Design',
        },
        {
          type: 'doc',
          id: 'scalardb-supported-databases',
          label: 'Supported Databases',
        },
        {
          type: 'doc',
          id: 'requirements',
          label: 'Requirements',
        },
        {
          type: 'doc',
          id: 'releases/release-notes',
          label: 'Release Notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quickstart',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'quick-start-overview',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Try Running Transactions Through the ScalarDB Core Library',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'getting-started-with-scalardb',
              label: 'Use ScalarDB Core',
            },
            {
              type: 'doc',
              id: 'getting-started-with-scalardb-by-using-kotlin',
              label: 'Use Kotlin',
            },
          ],
        },
        {
          type: 'category',
          label: 'Try Running Analytical Queries Through ScalarDB Analytics',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-analytics-postgresql/getting-started',
              label: 'Use ScalarDB Analytics with PostgreSQL',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-analytics-postgresql/installation',
              label: 'Install ScalarDB Analytics with PostgreSQL Locally',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Develop',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'develop-overview',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Run Transactions',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'data-modeling',
              label: 'Model Your Data',
            },
            {
              type: 'category',
              label: 'Run Through the CRUD Interface',
              collapsible: true,
              items: [
                { // To be created
                  type: 'doc',
                  id: 'run-transactions-through-scalardb-core-library',
                  label: 'Use the ScalarDB Core Library',
                },
              ],
            },
            {
              type: 'category',
              label: 'Advanced Configurations and Operations',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-benchmarks/README',
                  label: 'Run Benchmarks',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Run Analytical Queries',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-samples/scalardb-analytics-postgresql-sample/README',
              label: 'Use ScalarDB Analytics with PostgreSQL',
            },
          ],
        },
        {
          type: 'category',
          label: 'Run Non-Transactional Storage Operations',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'Run Through the CRUD Interface',
              collapsible: true,
              items: [
                { // To be created
                  type: 'doc',
                  id: 'run-non-transactional-storage-operations-through-library',
                  label: 'Use the ScalarDB Core Library',
                },
              ],
            },
            {
              type: 'doc',
              id: 'run-non-transactional-storage-operations-through-primitive-crud-interface',
              label: 'Run Through the Primitive CRUD Interface',
            },
          ],
        },
        {
          type: 'category',
          label: 'Create Sample Applications',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-samples/multi-storage-transaction-sample/README',
              label: 'Multi-Storage Transactions',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/microservice-transaction-sample/README',
              label: 'Microservice Transactions',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'add-scalardb-to-your-build',
              label: 'Add ScalarDB to Your Build',
            },
            {
              type: 'doc',
              id: 'configurations',
              label: 'ScalarDB Configurations',
            },
            {
              type: 'doc',
              id: 'api-guide',
              label: 'API Guide',
            },
            {
              type: 'doc',
              id: 'two-phase-commit-transactions',
              label: 'Two-Phase Commit Transactions',
            },
            {
              type: 'doc',
              id: 'multi-storage-transactions',
              label: 'Multi-Storage Transactions',
            },
            {
              type: 'doc',
              id: 'schema-loader',
              label: 'Schema Loader',
            },
            {
              type: 'category',
              label: 'Analytics',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-analytics-postgresql/scalardb-fdw',
                  label: 'ScalarDB FDW for PostgreSQL',
                },
                {
                  type: 'doc',
                  id: 'scalardb-analytics-postgresql/schema-importer',
                  label: 'PostgreSQL Schema Importer for PostgreSQL',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Migrate',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'schema-loader-import',
          label: 'Import Existing Tables',
        },
      ],
    },
    {
      type: 'category',
      label: 'Manage',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'backup-restore',
          label: 'Back Up and Restore Databases Used Through ScalarDB',
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshoot',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Error Codes',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-core-status-codes',
              label: 'ScalarDB',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
